# Use postgres/example user/password credentials
version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: postgresql
    ports:
      - '5432:5432'
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db: